# Generated by Django 4.2 on 2023-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_image', models.ImageField(blank=True, upload_to='static/product_image')),
                ('price', models.IntegerField()),
                ('shop', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=20)),
                ('products', models.CharField(default='[]', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, upload_to='static/logo')),
                ('products', models.ManyToManyField(null=True, related_name='shops', to='app.product')),
            ],
        ),
    ]
