# Generated by Django 4.2 on 2023-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_shop_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(null=True, related_name='shops', to='app.product'),
        ),
    ]
