# Generated by Django 4.2 on 2023-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shop_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcard',
            name='products',
        ),
        migrations.AddField(
            model_name='shopcard',
            name='products',
            field=models.CharField(default='', max_length=200),
        ),
    ]
