# Generated by Django 4.2 on 2023-06-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shop_products'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='index_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
    ]
